

spring:
  application:
    name: batch-practice

  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      platform: mysql

logging:
  level:
    org.springframework.batch: debug

server:
  port: 8181





